### ISSUE TITLE
Meet the Crew

### ISSUE THREAD

**Issue by 21jaina** [GlazedPineapple/anjali-website#2]
<p><b>A.J.</b><br/>
<i>17, she/her<br/>
editor-in-chief & contributor</i><br/>
The angsty teen, organizational wizard, jazz drummer, and Our Own Words founder who uses her talents to inflict peace, love, and poetry on the world. She has always loved writing because it gives her the ability to make messy things make a little bit more sense, and relies on imagery to capture fleeting emotional moments.</p>

<p><b>C.H.</b><br/>
<i>17, they/them<br/>
contributor</i><br/>
An enthusiast of cats and books whose raw and lyrical language gives them an outlet for their desires and emotions, often touching on themes of queer pride and different forms of love. </p>

<p><b>C.G.</b><br/>
<i>17, he/him<br/>
contributor</i><br/>
This makeup artist extraordinaire thrives on a bit of chaos and a lot of love, and the array of larger-than-life characters that populate his writing reflect that. </p>

<p><b>E.K.</b><br/>
<i>17, they/them<br/>
tech support & moral support</i> <br/>
The designer and curator of the Our Own Words website who makes sure all our content gets safely to you. Their love for computers (and the video games that come with them) is only rivaled by their love for their husky, Skipper.</p>

**Comment by GlazedPineapple** [comment]
This feature has been implemented
